version: "3.8"

services:
  mathgeneratorapi:
    build:
      context: .
      dockerfile: MathExamGenerator.API/Dockerfile
    container_name: mathgeneratorapi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=14.225.253.29;Database=MathExamGenerator;User Id=sa;Password=winnertech123@;TrustServerCertificate=True;
    ports:
      - "8888:8080"
    networks:
      - my_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=winnertech123@
    ports:
      - "1433:1433"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
