version: "3.8"

services:
  mathgeneratorapi:
    build:
      context: .
      dockerfile: MathExamGenerator.API/Dockerfile
    container_name: mathgeneratorapi
    depends_on:
      - redis
    environment:
      ConnectionStrings__DefaultDB: "Server=14.225.253.29,1433;Database=MathExamGenerator;User Id=sa;Password=winnertech123@;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=true"
      ConnectionStrings__Redis: "redis:6379,abortConnect=false"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8888:8080"
    networks:
      - my_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
